# Generated by Django 4.2.23 on 2025-07-25 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('is_distributed', models.BooleanField(default=False)),
                ('last_distribution_attempt', models.DateTimeField(blank=True, null=True)),
                ('distribution_status', models.CharField(default='Pending', max_length=100)),
            ],
            options={
                'verbose_name': 'Simulated Release',
                'verbose_name_plural': 'Simulated Releases',
            },
        ),
    ]
